// Classical story metadata for English, French, and German libraries
// These will be processed by AI to create bedtime-appropriate summaries and morals

export interface ClassicalStoryMeta {
  title: string;
  author: string;
  language: "en" | "fr" | "de";
  source: string;
  description: string; // Brief description to guide AI generation
}

export const englishClassics: ClassicalStoryMeta[] = [
  { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", language: "en", source: "Project Gutenberg", description: "A girl falls down a rabbit hole into a fantasy world" },
  { title: "Through the Looking-Glass", author: "Lewis Carroll", language: "en", source: "Project Gutenberg", description: "Alice steps through a mirror into an alternate world" },
  { title: "The Wonderful Wizard of Oz", author: "L. Frank Baum", language: "en", source: "Project Gutenberg", description: "Dorothy's journey to the magical land of Oz" },
  { title: "Peter Pan", author: "J. M. Barrie", language: "en", source: "Project Gutenberg", description: "The boy who never grows up and his adventures in Neverland" },
  { title: "The Wind in the Willows", author: "Kenneth Grahame", language: "en", source: "Project Gutenberg", description: "Adventures of animal friends by the riverbank" },
  { title: "The Velveteen Rabbit", author: "Margery Williams", language: "en", source: "Project Gutenberg", description: "A toy rabbit's journey to becoming real through love" },
  { title: "A Christmas Carol", author: "Charles Dickens", language: "en", source: "Project Gutenberg", description: "Scrooge's transformation through visits from three ghosts" },
  { title: "The Secret Garden", author: "Frances Hodgson Burnett", language: "en", source: "Project Gutenberg", description: "A girl discovers a hidden garden and helps it bloom" },
  { title: "Little Women", author: "Louisa May Alcott", language: "en", source: "Project Gutenberg", description: "Four sisters growing up during the Civil War" },
  { title: "The Jungle Book", author: "Rudyard Kipling", language: "en", source: "Project Gutenberg", description: "Mowgli raised by wolves in the Indian jungle" },
  { title: "Cinderella", author: "Charles Perrault", language: "en", source: "Project Gutenberg", description: "A kind girl helped by her fairy godmother to attend the ball" },
  { title: "Sleeping Beauty", author: "Charles Perrault", language: "en", source: "Project Gutenberg", description: "A princess cursed to sleep for a hundred years" },
  { title: "Little Red Riding Hood", author: "Charles Perrault", language: "en", source: "Project Gutenberg", description: "A girl's encounter with a wolf in the forest" },
  { title: "Bluebeard", author: "Charles Perrault", language: "en", source: "Project Gutenberg", description: "A curious wife discovers her husband's dark secret" },
  { title: "Puss in Boots", author: "Charles Perrault", language: "en", source: "Project Gutenberg", description: "A clever cat helps his master find fortune" },
  { title: "Beauty and the Beast", author: "Jeanne-Marie Leprince de Beaumont", language: "en", source: "Project Gutenberg", description: "A girl learns to see beyond appearances" },
  { title: "Hansel and Gretel", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "Two children lost in the forest find a gingerbread house" },
  { title: "Snow White", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A princess befriends seven dwarfs while hiding from her stepmother" },
  { title: "Rapunzel", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A girl with long hair trapped in a tower" },
  { title: "Rumpelstiltskin", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A girl must guess a magical creature's name" },
  { title: "The Frog Prince", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A princess's promise transforms a frog" },
  { title: "The Golden Goose", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A kind boy receives a magical goose" },
  { title: "The Fisherman and His Wife", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A magical fish grants wishes with consequences" },
  { title: "The Twelve Dancing Princesses", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A mystery of worn-out dancing shoes is solved" },
  { title: "The Goose Girl", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "A princess disguised as a goose girl reclaims her identity" },
  { title: "The Elves and the Shoemaker", author: "Jacob & Wilhelm Grimm", language: "en", source: "Project Gutenberg", description: "Magical elves help a poor shoemaker" },
  { title: "Aladdin and the Magic Lamp", author: "One Thousand and One Nights", language: "en", source: "Project Gutenberg", description: "A boy discovers a magical lamp with a powerful genie" },
  { title: "Ali Baba and the Forty Thieves", author: "One Thousand and One Nights", language: "en", source: "Project Gutenberg", description: "A woodcutter discovers a cave full of treasure" },
  { title: "The Seven Voyages of Sinbad", author: "One Thousand and One Nights", language: "en", source: "Project Gutenberg", description: "A sailor's adventures across magical seas" },
  { title: "The Fisherman and the Genie", author: "One Thousand and One Nights", language: "en", source: "Project Gutenberg", description: "A fisherman releases a trapped genie from a bottle" },
];

export const frenchClassics: ClassicalStoryMeta[] = [
  { title: "Le petit Chaperon rouge", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Une petite fille rencontre un loup dans la forêt" },
  { title: "Cendrillon", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Une jeune fille aidée par sa marraine fée" },
  { title: "La Belle au Bois dormant", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Une princesse endormie pour cent ans" },
  { title: "Le Chat botté", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Un chat malin aide son maître" },
  { title: "Le Petit Poucet", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Le plus petit de sept frères sauve sa famille" },
  { title: "Riquet à la Houppe", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Un prince laid mais spirituel" },
  { title: "Peau d'Âne", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Une princesse se cache sous une peau d'âne" },
  { title: "Les Fées", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Deux sœurs aux caractères opposés" },
  { title: "Les Souhaits ridicules", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Trois souhaits gaspillés" },
  { title: "La Barbe-Bleue", author: "Charles Perrault", language: "fr", source: "Wikisource", description: "Une femme découvre le secret de son mari" },
  { title: "Gracieuse et Percinet", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Une princesse et son prince fée" },
  { title: "La Belle aux cheveux d'or", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Une quête pour gagner le cœur d'une princesse" },
  { title: "L'Oiseau bleu", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Un prince transformé en oiseau bleu" },
  { title: "Finette Cendron", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Une princesse maligne déjoue les plans" },
  { title: "Le Nain jaune", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Un nain jaune et une princesse" },
  { title: "La Chatte blanche", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Une chatte blanche enchantée" },
  { title: "La Belle et la Bête", author: "Jeanne-Marie Leprince de Beaumont", language: "fr", source: "Wikisource", description: "L'amour au-delà des apparences" },
  { title: "La Cigale et la Fourmi", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "La cigale qui chante l'été" },
  { title: "Le Corbeau et le Renard", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Un renard flatte un corbeau" },
  { title: "Le Loup et l'Agneau", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "La loi du plus fort" },
  { title: "Le Lièvre et la Tortue", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Rien ne sert de courir" },
  { title: "Le Rat de ville et le Rat des champs", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Deux rats comparent leurs vies" },
  { title: "Le Lion et le Rat", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Un petit rat aide un grand lion" },
  { title: "Le Chêne et le Roseau", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "La force et la flexibilité" },
  { title: "La Grenouille et le Bœuf", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Une grenouille veut se faire aussi grosse" },
  { title: "Le Loup et le Chien", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Liberté contre confort" },
  { title: "Le Laboureur et ses enfants", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Le travail est un trésor" },
  { title: "Le Renard et la Cigogne", author: "Jean de La Fontaine", language: "fr", source: "Wikisource", description: "Tel est pris qui croyait prendre" },
  { title: "Le Nain bleu", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Les aventures d'un nain bleu" },
  { title: "La Biche au bois", author: "Marie-Catherine d'Aulnoy", language: "fr", source: "Wikisource", description: "Une princesse transformée en biche" },
];

export const germanClassics: ClassicalStoryMeta[] = [
  { title: "Aschenputtel", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Mädchen findet mit Hilfe ihrer verstorbenen Mutter das Glück" },
  { title: "Schneewittchen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Eine Prinzessin und sieben Zwerge" },
  { title: "Dornröschen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Die schlafende Prinzessin" },
  { title: "Rotkäppchen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Mädchen besucht ihre Großmutter" },
  { title: "Hänsel und Gretel", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Zwei Kinder finden ein Lebkuchenhaus" },
  { title: "Rumpelstilzchen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Mädchen muss einen Namen erraten" },
  { title: "Der Froschkönig", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Frosch wird zum Prinzen" },
  { title: "Der Fischer und seine Frau", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Fisch erfüllt Wünsche" },
  { title: "Das tapfere Schneiderlein", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein mutiger Schneider" },
  { title: "Die Gänsemagd", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Eine Prinzessin als Gänsemagd" },
  { title: "Die zwölf Brüder", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Zwölf Prinzen werden zu Raben" },
  { title: "Die sechs Schwäne", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Sechs Brüder als Schwäne" },
  { title: "Der goldene Vogel", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Die Suche nach dem goldenen Vogel" },
  { title: "Die Wichtelmänner", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Kleine Helfer in der Nacht" },
  { title: "Die Bremer Stadtmusikanten", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Vier Tiere auf dem Weg nach Bremen" },
  { title: "Der Wolf und die sieben Geißlein", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Wolf und sieben junge Ziegen" },
  { title: "Die Bienenkönigin", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Drei Brüder und eine Bienenkönigin" },
  { title: "Die goldene Gans", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Eine magische Gans" },
  { title: "Der singende Knochen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Knochen offenbart die Wahrheit" },
  { title: "Von dem Machandelboom", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Wacholderbaum und seine Geheimnisse" },
  { title: "Die Sterntaler", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein armes Mädchen wird belohnt" },
  { title: "Die Nixe im Teich", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Eine Wassernixe im Teich" },
  { title: "Das Waldhaus", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein Haus im Wald" },
  { title: "Der Eisenofen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein verzauberter Prinz im Eisenofen" },
  { title: "Das Eselein", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein besonderes Eselchen" },
  { title: "Die Kristallkugel", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Die Suche nach der Kristallkugel" },
  { title: "Das Wasser des Lebens", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Drei Brüder suchen das Wasser des Lebens" },
  { title: "Die drei Vögelchen", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Drei magische Vögel" },
  { title: "Der alte Sultan", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Ein treuer alter Hund" },
  { title: "Schneeweißchen und Rosenrot", author: "Brüder Grimm", language: "de", source: "Wikisource", description: "Zwei Schwestern und ein Bär" },
];
